language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - AWS_KEY=AKIAQ2EYLEMJ3FI5RYMT
    - secure: "q/nkwLE0ct/4WVtqkBbyVURhnLwupi0ZdRw45PsUcp7LvEtR5LumLl8hsWsvPfSvFsrfE/A3PcXKtOyLFkrdX4bCzcFh3PmN41fiupFaWwNpIsz2khWFLHyGCL8wtnVWl2JieMQgFhXL7qClnSH2lkaW4lZc3wGlORiEPsq5JVx9C+Wdqji5vV/qZk5w3tt2EBGSa9CEK3YcLUOIScRHENazioAv7hgJk6vpatOXh72FEpdeIrZnCK4OpzOOnrFnh5lIsStdMaeujJVV0ZXR1PpVnSAXZVgYsgNMzYJnvPoJSuEpokvxtyCp+ftBBZu85DHQx84PE4yLoHgB0LI0iLYpQ3kkcaXYewQ56TflPuowAbshjVuJh0clJSfCfJR+oeS60eoXzZePPtL604cLR6dkNMvPRzW634K+d70TSb/DMuCap79qgi0dZXEWk59yFHTXcuxj52S7HTe6XlEHgRlcxnbHUBuqabKEKSW7Ytue1Acfa+2676fUMnsUl5hkxannUZrDYqFSEpfQPUH8KnueczmwZBlmRwhXq4eG5ZbqM+rmgraPnA+/jYkHkHlixqhQM7XmN2V6qV+ITdrElYpi+kIFo2p9IrtB2Um3cqEWOWRgisy2rWxSCdFV1spQokuF4TaZbC5wMqoxx6zjWJb53yxcpGN6Q4d+jo7PCKg="
    - STAGE_REACT_APP_GLOBAL_REGISTRY_BASE_URL=https://stage-backend.global-registry.org

before_script:
  - |
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      for prefixed_envvar in ${!PROD_*}; do
        eval export ${prefixed_envvar#PROD_}="${!prefixed_envvar}"
      done
    else
      for prefixed_envvar in ${!STAGE_*}; do
        eval export ${prefixed_envvar#STAGE_}="${!prefixed_envvar}"
      done
    fi

script:
  - yarn test --coverage
  - yarn build

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

deploy:
  - provider: s3
    access_key_id: "$AWS_KEY"
    secret_access_key: "$AWS_SECRET"
    bucket: global-registry.org
    local_dir: build
    acl: public_read
    cache_control: max-age=300
    skip_cleanup: true
    on:
      branch: master

  - provider: s3
    access_key_id: "$AWS_KEY"
    secret_access_key: "$AWS_SECRET"
    bucket: stage.global-registry.org
    local_dir: build
    acl: public_read
    cache_control: max-age=300
    skip_cleanup: true
    on:
      branch: staging
